# Segments: (id, [(caption text, tts text or None=same)])
SEG = [
 ("hook",   [("Bu videodaki her şeyi tek başıma yaptım.", None)]),
 ("kimim",  [("Ben Furki.", "Ben Furki."),
             ("Gündüzleri yapay zekâ ajanlarının üstünde çalıştığı altyapıyı kuruyorum.", None),
             ("Akşamları ise oyun yapıyorum.", None),
             ("Hepsini size üç dakikada göstereyim.", None)]),
 ("k_oyun", [("Önce oyunlar. Dördünü de Godot ile yaptım.", None), ("Hepsi tarayıcıda, ücretsiz.", None)]),
 ("tek",    [("Tek Tuş Koşu.", None), ("Tek bir tuşla zıplıyorsun, gerisi refleks.", None),
             ("Müziğin ritmiyle oynanan bir modu bile var.", None),
             ("Her gün herkesin aynı parkuru koştuğu bir günlük koşusu da var.", None)]),
 ("kanca",  [("Kanca.", None), ("Halatı at, sallan, doğru anda bırak.", None),
             ("Her bölümün altın madalya süresini, oyunu kendisi oynayan bir bot ölçüyor.", None),
             ("Altını alırsan, o botun koşusu hayalet olarak yanında yarışıyor.", None)]),
 ("yc",     [("Yerçekimi Çevir.", None), ("Zıplama yok.", None),
             ("Tek hamlen, yerçekimini ters çevirmek. 20 bölüm.", "Tek hamlen, yerçekimini ters çevirmek. Yirmi bölüm."),
             ("Her gün değişen bir günün bölümü de var.", None)]),
 ("derin",  [("Derin Kazı.", None), ("250 metre aşağıdaki çekirdeğe in.", "İki yüz elli metre aşağıdaki çekirdeğe in."),
             ("Ama deprem geliyor: yüzeye mi çıkacaksın, derinde mi kalacaksın?", None),
             ("Karanlıkta ilerliyorsun; ışığının gördüğü kadarını biliyorsun.", None)]),
 ("k_web",  [("Sonra tarayıcı için yaptıklarım.", None)]),
 ("nova",   [("Nova Drift. Işık tünelinde bir uzay koşusu.", None), ("Seslerinin tamamı kodla üretiliyor.", None), ("Her gün herkes aynı koşuyu oynuyor.", None)]),
 ("masal",  [("Masal. Çocuğun adına, yaşına ve şehrine göre yazılan bir uyku masalı.", None),
             ("Boyama sayfası da içinde.", None)]),
 ("ajan",   [("Türkçe Ajanlar.", None), ("İçinde 70 tane Türkçe ajan var.", "İçinde yetmiş tane Türkçe ajan var."),
             ("Kurmadan önce tarayıcıda aranabiliyor.", None)]),
 ("k_hari", [("Ve bir soru: yakınımda ne var?", None)]),
 ("harita", [("Buradane, Türkiye'nin 81 ilinden 167.829 gerçek yeri tek haritada topluyor.",
              "Buradane, Türkiye'nin seksen bir ilinden, yüz altmış yedi bin sekiz yüz yirmi dokuz gerçek yeri, tek haritada topluyor."),
             ("Tuvalet, su, park, eczane.", None),
             ("“Ücretsiz tuvalet” yazıyorsun, en yakın 19 tanesini görüyorsun.", "Ücretsiz tuvalet yazıyorsun, en yakın on dokuz tanesini görüyorsun.")]),
 ("k_arac", [("Bir de işin görünmeyen tarafı var:", None), ("başkalarının işini denetleyen araçlar.", None)]),
 ("arac",   [("MCP Vet, bir MCP sunucusunu kurmadan önce kodunu okuyor, hiçbir şeyi çalıştırmıyor.",
              "Em Si Pi Vet, bir Em Si Pi sunucusunu kurmadan önce kodunu okuyor, hiçbir şeyi çalıştırmıyor."),
             ("Godot oyunlarındaki kırık bağlantıları, editörü açmadan bulup onarıyor.", None),
             ("Bir diğeri de bir projenin tanıtım sayfasındaki kurulum komutlarını ve bağlantıları tek tek deniyor.", None)]),
 ("rakam",  [("Toplamda 28 açık kaynak proje, 5.247 test, 1.096 commit.",
              "Toplamda yirmi sekiz açık kaynak proje, beş bin iki yüz kırk yedi test, bin doksan altı komit."),
             ("Her sayı, onu basan test koşusuna bağlı.", None)]),
 ("son",    [("Hepsi açık kaynak, hepsi ücretsiz.", None), ("Link profilimde.", None),
             ("Bir sonrakini görmek istiyorsan takip et.", None)]),
]
